name: metis-reward-submitter

services:
  submitter:
    image: metisdao/reward-submitter:${VERSION:-dev}
    build:
      context: .
      dockerfile: Dockerfile
      target: reward-submitter
      platforms:
        - linux/arm64
        - linux/amd64
